### ISSUE TITLE
Invalid Application-ID or API

### ISSUE THREAD

**Issue by webecks** [w3bdesign/wp-algolia-woo-indexer#175]
I have this problem, if I use client's API key & Application ID I can't send products to Algolia (debug error attached).
But if I use the API key & Application ID from my own account there is no problem, sent successfully.

Then I tried using WP Search with Algolia, with my client's API key & Application ID, it also had no problem syncing.

My client's account is on a trial period and my own account is free, does that matter?

```
[28-Apr-2023 01:27:01 UTC] PHP Fatal error:  Uncaught Algolia\AlgoliaSearch\Exceptions\BadRequestException: Invalid Application-ID or API key in /path/wp-content/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:210
Stack trace:
#0 /path/wp-content/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(158): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->handleResponse()
#1 /path/wp-content/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(78): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->request()
#2 /path/wp-content/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/SearchClient.php(205): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->read()
#3 /path/wp-content/plugins/algolia-woo-indexer/classes/class-send-products.php(71): Algolia\AlgoliaSearch\SearchClient->listApiKeys()
#4 /path/wp-content/plugins/algolia-woo-indexer/classes/class-send-products.php(150): Algowoo\Algolia_Send_Products::can_connect_to_algolia()
#5 /path/wp-content/plugins/algolia-woo-indexer/classes/class-algolia-woo-indexer.php(211): Algowoo\Algolia_Send_Products::send_products_to_algolia()
#6 /path/wp-includes/class-wp-hook.php(308): Algowoo\Algolia_Woo_Indexer::maybe_send_products()
#7 /path/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#8 /path/wp-includes/plugin.php(517): WP_Hook->do_action()
#9 /path/wp-admin/admin.php(175): do_action()
#10 /path/wp-admin/options-general.php(10): require_once('...')
#11 {main}
  thrown in /path/wp-content/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php on line 210
```

**Comment by w3bdesign** [comment]
Hi @webecks 

You need to ensure the application ID and API key is set correctly. 

See below for where to set it and where to find the information you need in Algolia.

I am not sharing my actual API keys, just the screens where you can find them.

![image](https://user-images.githubusercontent.com/45217974/235051425-ab55281a-193a-4d94-9138-9a262e41cea3.png)

![image](https://user-images.githubusercontent.com/45217974/235051510-46627c31-ae94-49a3-b0fb-15723971e5d1.png)

![image](https://user-images.githubusercontent.com/45217974/235051575-fa9b4265-b97a-487f-8a81-06ab2ccd9e83.png)
